# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 870a8727ae920453acdb43803ec899f991c6d2d054a0230c308774b710e84e180b13ffa8a75fe003e63cfa15505cf97e2d26fd0afdeb6f8cc038ca1f46008292

test:
  secret_key_base: 983178cef9507f06ca6c860b86bb84d67df04720c692a6516bf3384816649eb3cc89f787e2076e5e5181c17dc632b7baca1bc9419f4d3434ca6894b270ef7d28

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
